### ISSUE TITLE
[plugin-images] add option to remove the padding-bottom from ejs wrapper

### ISSUE THREAD

**Issue by noxasch** [Elderjs/plugins#106]
This element class attribute cannot be change with `cssString` option since it is hardcoded into the element itself in `utils/imageStore.js`. I'm not sure about the use cases here, but it break my styling by adding 29% padding bottom and other element down.

```js
let pictureWithWrap = `<div class="ejs" style="padding-bottom: ${
    Math.round((file.height / file.width) * 10000) / 100
}%;">`;
```

My suggestion is to add a config option like `ejsPaddingBottom: false` and you can easily opt out from the paddingBottom

```js
let pictureWithWrap = `<div class="ejs" 
    ${plugin.config.ejsPaddingBottom ? 
     'style="padding-bottom:' + Math.round((file.height / file.width) * 10000) / 100 + '%;' : ''}>`;
```

**Comment by nickreese** [comment]
We’ll want to think about removing this. This is part of how we reduce cumulative layout shift (a core web vital). I’ll consider this when doing the refactoring as well.

**Comment by nickreese** [comment]
I'm concerned about API creep as at some point we may change the way that the plugin handles responsive images. I think the best bet is that if `cssString:false` we remove all css generated by the plugin. It forces the user to put their css elsewhere and we can carry forward the philosophy that the plugin shouldn't generate css unless `typeof cssString === 'string'`.

**Comment by nickreese** [comment]
This will be shipped with the next minor release. Working on a handful of the other plugins and want to bundle all of the major changes into a `minor` package bump as all of the packages are tied to the same version number.
