### ISSUE TITLE
[plugin-images] Only add lazyload customJsStack to file that use the plugin and add option to disable placeholder image

### ISSUE THREAD

**Issue by noxasch** [Elderjs/plugins#107]
As of it current state, it will generate lazyload js to every html file in public directory whether it have images generated by the plugin or not,  my proposal based on what i've been experimented that work, we can check if it contain part of the shortcodes for example `data.html.includes('{{picture')` in the `elderPluginImagesManagevanillaLazy` hook.

the second one is to disable placeholder completely for user that doesn't want to use javascript at all on the pages (if it is not needed), for this i propose that we add `disablePlaceholder: false` by default and we check the config before injecting the placeholder code. However we can also add an option for user to add their own `jsString` and check if `addVanillaLazy: false` and `jsString` is undefined or empty, we can disable the placeholder as well in the `imageStore`.

I can work on the PR if needed.

**Comment by nickreese** [comment]
@noxasch I am working on a major refactor of the plugin as we speak so that the image generation can be exposed as a function and external manifest files can be imported. 

(We’ve got a dash where our team uploads photos). 

I’ll try and review the PR today.

**Comment by nickreese** [comment]
Pushed code with these fixes, will release shortly:

- `placeholder: false` will remove the placeholder. 
- the plugin will no longer add css/js unless required.
