### ISSUE TITLE
@elderjs/plugin-images - Deleting image from source folder not reflected in generated files 

### ISSUE THREAD

**Issue by meigo** [Elderjs/plugins#30]
Deleting (or renaming) image files from source folder doesn't remove related generated images and entries from ejs-image-manifest.json. Is this intended behaviour?

**Comment by meigo** [comment]
Ok. As a result of fixing this issue [github.com/Elderjs/plugins/issues/31](https://github.com/Elderjs/plugins/issues/31) only the image sizes from plugin configuration will be copied over to public folder during the build, so it in principle fixes this issue as well. 

Image cache itself is persistent and all the sizes once generated will stay there and this is probably for performance reasons.

Some notes:

### Added these lines to .gitignore to keep cache files out of repository

```
/images/sizes/
/images/*.json
```

### Cleaning cache

Added explicitly default cache related values to elder.config.js

```js
imageManifest: '/images/ejs-image-manifest.json',
cacheFolder: '/images/sizes/',
```
	  
and created package script to clear the cache when it feels appropriate

```js
//src/cleanImageCache.js

const del = require('del');
const path = require('path');
const { getConfig } = require('@elderjs/elderjs');
a
const { rootDir, plugins } = getConfig();

console.log(' Clearing out image cache.');

if (plugins['elderjs-plugin-images'] !== undefined) {
  const plugin = plugins['@elderjs/plugin-images'];
  if (plugin.imageManifest !== undefined) {
    del.sync(path.join(rootDir, plugin.imageManifest));
  }
  if (plugin.cacheFolder !== undefined) {
    del.sync(path.join(rootDir, plugin.cacheFolder));
  }
}
```


```console
node ./src/cleanImageCache.js
```

**Comment by nickreese** [comment]
@meigo We should add a check that update the manifest but for now, just delete it and the plugin will rebuild it without recreating the images. 

I've added your scripts above to the readme.

**Comment by meigo** [comment]
Thanks.
Small mistake in script above, sorry about this, should be

```js
//src/cleanImageCache.js

const del = require('del');
const path = require('path');
const { getConfig } = require('@elderjs/elderjs');
a
const { rootDir, plugins } = getConfig();

console.log(' Clearing out image cache.');

if (plugins['@elderjs/plugin-images'] !== undefined) {
  const plugin = plugins['@elderjs/plugin-images'];
  if (plugin.imageManifest !== undefined) {
    del.sync(path.join(rootDir, plugin.imageManifest));
  }
  if (plugin.cacheFolder !== undefined) {
    del.sync(path.join(rootDir, plugin.cacheFolder));
  }
}
```

**Comment by nickreese** [comment]
@meigo Thanks!
