### ISSUE TITLE
@elderjs/plugin-images - Custom config props not replacing default props properly

### ISSUE THREAD

**Issue by meigo** [Elderjs/plugins#31]
Default config array props

```json
widths: [1280, 992, 768, 576, 400, 350, 200], 
scales: [1, 2],
```

are not replaced with custom values from elder.config.js

```json
widths: [1000, 750, 500], 
scales: [1],
```

but updated resulting config values like this

```json
widths: [1000, 750, 500, 576, 400, 350, 200], 
scales: [1, 2],
```

**Comment by nickreese** [comment]
@meigo this will be an issue with lodash’s defaultsDeep.

We’ll need to remove the defaults and if the array received by the init function is empty then we populate a default. 

I’m slammed for the next few days but will try and bundle these together. If you wanted to they and pull together a PR I’d gladly code review and merge it. 

The markdown plugin had a similar issue.

**Comment by meigo** [comment]
[github.com/Elderjs/plugins/pull/32](https://github.com/Elderjs/plugins/pull/32)

**Comment by nickreese** [comment]
@meigo thank you for this. Will push a release today.
