### ISSUE TITLE
Unexpected Token

### ISSUE THREAD

**Issue by sandman18** [Elderjs/plugins#36]
Hello, after installing the plugin, I'm trying to use  an image with {{picture src="/img/Myimage.jpg" /}}.

I'm getting an unexpected token error for src.  Is the shortcode only to be used in a markdown file?  Or can we use it in svelte files as well?

**Comment by nickreese** [comment]
@sandman18 Sorry I missed this. You can use them in Svelte but you've gotta use a helper:

```svelte
@html helpers.shortcode({name: 'box', props: {class: "yellow"}, content: "content string here" })
```

**Comment by sandman18** [comment]
Hey Nick, so do you then have to import helpers from somewhere?

I created a shortcode:

` {
  shortcode: 'picture',
    run: async ({ src }) => {
      return {
        html: `{{picture src="${src}"}}`
      }
    },`

Added:
` {@html helpers.shortcode({name: 'picture',src:src})}`
to svelte file, but it looks like I need to import helpers.

**Comment by nickreese** [comment]
@sandman18 `helpers` is a prop that `Layout.svelte` and `RouteName.Svelte` get. 

`export let helpers;` should get you access to it.

**Comment by sandman18** [comment]
Okay.  So I added 
`export let helpers`
and I am getting a TypeError cannot read property shortcode of undefined.

Do I need to pass the helpers prop into the component that is exporting helpers?

**Comment by nickreese** [comment]
@sandman18 If you aren't in your `/src/routes/routeName/RouteName.svelte` then I'd actually do a `const thing = helpers.shortcode({name: 'picture',src:src})` then pass the HTML down... especially if you're hydrating. If you aren't hydrating you can pass it down.
