### ISSUE TITLE
Enhancing the image plugin with BlurHash

### ISSUE THREAD

**Issue by kevmodrome** [Elderjs/plugins#38]
https://github.com/woltapp/blurhash

TL;DR: Images are encoded into base 83 strings that are then sent with the HTML (probably as an attribute on the image). The client takes the string and decodes it into a beautiful canvas that acts as a placeholder until the real image is downloaded. Not sure how hard/complicated it would be to add support for this to the image plugin?

**Comment by nickreese** [comment]
@kevmodrome nice find and a cool idea. The image plugin already does low quality image placeholders and svg placeholders out of the box. 

It may not be documented but it is there. (Lol)

This solution seems to save on html size but adds a client and server dependency for a similar effect.
