### ISSUE TITLE
Reload plugin seems to have hardcoded reference to localhost

### ISSUE THREAD

**Issue by talha-asad** [Elderjs/plugins#40]
https://github.com/Elderjs/plugins/blob/8e1ce6e6c98b4078f0cac098dc909c642b5649cd/packages/browser-reload/index.js#L50

Shouldn't this and the other reference to localhost be what is set as `origin` from the main elder config?

**Comment by nickreese** [comment]
@talha-asad this is really designed for dev only. I wouldn't suggest to use it during prod but it could use the origin prop and fall back to localhost if not set. 

Updating the docs and adding a check to make sure  `process.env.NODE_ENV` isn’t prod is probably wise.

**Comment by talha-asad** [comment]
Makes sense, we do some of our local dev while using a pseudo hostname that resolves to 127.0.0.1 or a lan ip, I think using origin value here while it's not set in production would make sense. I'll try and put a pull request up for this.

**Comment by nickreese** [comment]
@talha-asad Nice! Honestly I’m a dev only out of my own necessity so you’ll probably see stuff like this where I’m just not aware how other people solve the problems. :) This network setup is a goo example. Never considered that. 

Historically been in the CEO/marketing role and only really been writing meaningful code for less than 2 years. Lots to learn still. :)

**Comment by nickreese** [comment]
@talha-asad fix pushed for this in `v0.1.13`
