### ISSUE TITLE
@elderjs/plugin-markdown - syntax highlighting not working

### ISSUE THREAD

**Issue by fli** [Elderjs/plugins#45]
I'm trying to use syntax highlighting by setting `useSyntaxHighlighting` in the plugin config.
When I build I get this stacktrace:

```
Error: `processSync` finished async. Use `process` instead
    at assertDone (.../node_modules/unified/index.js:469:11)
    at Function.processSync (.../node_modules/unified/index.js:401:5)
    at Object.init (.../node_modules/@elderjs/plugin-markdown/index.js:58:60)
    at new Elder (.../node_modules/@elderjs/elderjs/build/Elder.js:77:24)
    at Object.<anonymous> (.../src/server.js:10:15)
```

I think it's because the `rehype-shiki` plugin is asynchronous and [`unified` will throw if there is an asynchronous plugin and you run it synchronously](https://github.com/unifiedjs/unified#processorprocesssyncfilevalue), which is what it's doing in the plugin `init` function.

Am I missing something?

**Comment by nickreese** [comment]
I'll investigate. @sw-yx any ideas here?

**Comment by fli** [comment]
I got it working by making my own `rehype-shiki` locally that looks like this. The syntax tree that gets passed in is a [Markdown](https://github.com/syntax-tree/mdast) one and not an [HTML](https://github.com/syntax-tree/hast) one which changed a few things. Also forced the highlighter function to be synchronous.

Pretty hacky though! Might be another way?

```javascript
const shiki = require('shiki')
const visit = require('unist-util-visit')
const deasync = require('deasync')

module.exports = (options) => {
  const settings = options || {}
  const theme = settings.theme || 'nord'
  let shikiTheme
  let highlighter

  try {
    shikiTheme = shiki.getTheme(theme)
  } catch (_) {
    try {
      shikiTheme = shiki.loadTheme(theme)
    } catch (_) {
      throw new Error('Unable to load theme: ' + theme)
    }
  }

  shiki
    .getHighlighter({
      theme: shikiTheme,
    })
    .then((res) => (highlighter = res))
  deasync.loopWhile(() => !highlighter)

  return (tree) => {
    visit(tree, 'code', visitor)
  }

  function visitor(node, _, parent) {
    if (!parent) {
      return
    }

    const lang = node.lang
    if (!lang) {
      return
    }

    node.value = highlighter.codeToHtml(node.value, lang)
    node.type = 'html'
  }
}
```

**Comment by sw-yx** [comment]
fwiw we [locally vendor rehype-shiki](https://github.com/Elderjs/plugins/blob/master/packages/markdown/rehype-shiki.js) for a bunch of reasons (it is not maintained) - and what i wrote put in here is simply what worked for me on my setup of elderjs - i have not tested this from scratch so totally possible that it's broken for a fresh user right now. @fli want to send in a PR to fix with your code?

**Comment by nickreese** [comment]
@fli @sw-yx exploring making plugin init async. Too many times I've encountered similar issues.

**Comment by nickreese** [comment]
@fli I've got a PR here for async plugin init. Would really simplify things. https://github.com/Elderjs/elderjs/issues/69

This has been a refactor I've been wanting to do for a while. I'm slammed this week, but if we can get the tests working and covering the new behavior and we'll hopefully get this merged in.

**Comment by fli** [comment]
Legend @nickreese.
@sw-yx my pleasure, will get one in once I test it with the async plugin init.

**Comment by nickreese** [comment]
@fli async plugin init is shipped.

**Comment by fli** [comment]
Sweet, PR here #47
