### ISSUE TITLE
@elderjs/plugin-images - Long build times due to image processing

### ISSUE THREAD

**Issue by tweety101** [Elderjs/plugins#51]
This is the static site builder I have been waiting for! Truly static Svelte, selective hydration, and the hooks system are awesome. 

The only problem is that the images plugin seems to take a lot longer to process than the Gatsby alternative.

I used the standard settings and folders: 
`'@elderjs/plugin-images': {
      folders: [
        {
          src: '/images/*', // glob of where your original images are. Relative to rootDir/process.cwd() defined in your elder.config.js. Careful with **.
          output: '/images/', // where files should be put within the distDir defined in your elder.config.js.
        },
      ],
    },`

Even with 7 images, it takes 4 minutes to build on Netlify. Most of that is spent on processing the images:

<img width="1179" alt="Screen Shot 2020-11-03 at 10 01 23 AM" src="https://user-images.githubusercontent.com/39607504/98001364-8c028f80-1dbb-11eb-90dc-c562b18fd934.png">

The real site has several hundred images and is going to take forever to build. 

Any idea what I am doing wrong or how it can be made faster? 

Thanks!

**Comment by nickreese** [comment]
@tweety101 Netlify build envs are single core. Build it in a local dev env, make sure you commit the image-manifest, then push to Netlify. 

Builds should only be slow if the manifest is missing or hasn't been built.

**Comment by tweety101** [comment]
Thanks, Nick! I will try that. 

Something related to the images plugin but different from this issue:
Currently, the image helper inserts two <div> around the image. 
This causes issues with images from a Markdown file that are wrapped with a p or a tag. 
The image is rendered outside of the enclosing p or a by the browser so images links don't work and the formatting changes. 

Modifying the div tags to span in the imageStore.js seems to work great in both the Markdown content and for the helper. 
Would it make sense to change that in the plugin?
