### ISSUE TITLE
@elderjs/plugin-sitemap excluded routes

### ISSUE THREAD

**Issue by meigo** [Elderjs/plugins#52]
Is there any reason sitemap plugin generates sitemap-[slug].xml files with empty urlset for excluded routes that will also be included in the main sitemap.xml? Not sure if it's valid or not but wouldn't it be cleaner to just not generate them?

**Comment by nickreese** [comment]
@meigo good point. We haven't hit this issue. The overall plugin could probably be optimized. If you wanted to take a stab I'll gladly review the PR. :)

**Comment by meigo** [comment]
Right, here: https://github.com/Elderjs/plugins/pull/54

Maybe exclusion should be elaborated more in readme.

For example excluding 'green' route
```js
exclude: ['green'],
```
would excude all routes starting with 'green', also 'greenland' and 'green-eggs'

'green' route could be explicitly excluded with
```js
exclude: ['green/'],
```
Also nested routes or specific slugs of route could be excluded with
```js
exclude: ['green/', 'greenland/polar-bear'],
```

etc

**Comment by nickreese** [comment]
@meigo Thank you for the PR, you're right. I'll update the readme. We may want to reconsider this implementation though long term.
