### ISSUE TITLE
@elderjs/plugin-images - change helper's inserted html to better work with Markdown

### ISSUE THREAD

**Issue by tweety101** [Elderjs/plugins#53]
Hi, 

When using the images plugin together with the Markdown plugin, the inserted `<div>` containers for the images break out of the paragraphs and links from the Markdown. 

The images plugin inserts something like this: `<div class="ejs" style="padding-bottom: 45.73%;">....`

But, paragraphs tags can't contain `<div>`

`<span>`tags worked great as a replacement. 

 Would it make sense to change that in the plugin?

**Comment by nickreese** [comment]
@tweety101 Hmm, good question. 

I think an easier solution is to add https://github.com/remarkjs/remark-unwrap-images to the remark pipeline.

Can you try this in the markdown plugin's config and see if it solves the issue?

**Comment by tweety101** [comment]
Hi @nickreese,

I can't get it to work. The plugin is active and processing the markdown but doesn't detect any images. 
I think this happens because the images are replaced with the images shortcode  {{picture src="" alt="" /}} before going through the remark plugins. 

The remark-unwrap-images plugin doesn't recognize the shortcodes and doesn't do anything. 

What do you think?

**Comment by nickreese** [comment]
@tweety101 Hmm, you're right. It is processed before the remark pipeline. I'm open to ideas or PRs but changing the wrapping output seems like a bad option as it would likely break other user's implementations. 

It seems moving the replacement of markdown images to a remark plugin is probably ideal.

I'm not a remark expert but if you wanted to give a PR a spin happy to review the code. I'd look at how the `remark-unwrap-images` plugin works (https://github.com/remarkjs/remark-unwrap-images/blob/main/index.js) and see if we can move the image/shortcode replacement to remark.

**Comment by nickreese** [comment]
@tweety101 pushed a fix. By wrapping the shortcode in a `<div>` we can prevent it from being handled as a `<p>`.

**Comment by tweety101** [comment]
Nice, I hadn't thought of that. 

My site uses a lot of product images wrapped in links. 
For these, this solution doesn't work, unfortunately. 

I will probably just make a copy of the images plugin since that's pretty easy with ElderJs. 

Either way, thanks for the help!
