### ISSUE TITLE
[plugin-images] min-width on source is causing images to have resolution < size

### ISSUE THREAD

**Issue by Apollinaire** [Elderjs/plugins#60]
The sources inside a <picture> element rendered after a {{picture}} shortcode have a min-width equal to the width of the image inside their srcset. 
For the following `widths` setting : `[1000, 500, 300]` if the width of the element is 950px, the original image used will be 500px wide, and we will be losing quality.
So I think you want to offset the min-width setting to be the next lowest width, to turn this: 
```html
<picture>
  <source srcset="cat-1000.jpg" media="(min-width: 1000px)">
  <source srcset="cat-500.jpg" media="(min-width: 500px)">
  <source srcset="cat-300.jpg" >
</picture>
```
into this: 
```html
<picture>
  <source srcset="cat-1000.jpg" media="(min-width: 500px)">
  <source srcset="cat-500.jpg" media="(min-width: 300px)">
  <source srcset="cat-300.jpg" >
</picture>
```
This will mean that the image loaded is the smallest possible, without being smaller than the rendered element.

**Comment by nickreese** [comment]
@Apollinaire You're spot on. Happy to take a PR for this.
