### ISSUE TITLE
@elderjs/plugin-images - handling external images

### ISSUE THREAD

**Issue by BetaConnector** [Elderjs/plugins#65]
Hey, I am using strapi (https://strapi.io/) for a blog as a part of my site.

Strapi holds the ressources. On generating the static content my plan is to download the images.

Are there any ideas how to handle external ressources? Saving them manually does not sounds like fun :)

Thanks in advanced - Alex

**Comment by nickreese** [comment]
@BetaConnector You could write an adapter to pull the resources down before build. Not many options besides that or finding a way to proxy the images and update the manifest accordingly. 

Both of these are outside the scope of the plugin.
