### ISSUE TITLE
[Seo-check]: add ability to disable it during dev mode and generate a full report at build time

### ISSUE THREAD

**Issue by kiuKisas** [Elderjs/plugins#90]
In my company, as I don't manage the content of the site, I don't need to be warn about most of the seo-check. It could be more handy to have a final report during build time. What I actually think of for my use case is to send a report to a slack channel at every build.

- [ ] seo-check is a bit verbose in `dev` mode, we should be able to disable it.
- [ ] in `build` mode, generate a full report and print a resume instead of printing it for each routes

**Comment by nickreese** [comment]
Agreed on both points. Working on those next. Main issue is that builds split request generation between processes and plugins don’t have a shared closure there. Will probably end up globbing the public html.

**Comment by nickreese** [comment]
@kiuKisas Build mode is done. You could do a `NODE_ENV=production` check in your `elder.config.js` to turn the plugin on/off. Or we can add a flag.

**Comment by nickreese** [comment]
Try:

```js
  '@elderjs/plugin-seo-check': {
    display: process.NODE_ENV === production ? ['errors', 'warnings']: [], // disables reporting unless you in production building.
    },
```

**Comment by kiuKisas** [comment]
That was fast, thank's :+1:  
I'll give a try today
