### ISSUE TITLE
Expose markdown remark plugin defaults via an export

### ISSUE THREAD

**Issue by orta** [Elderjs/plugins#93]
I thought I might be able to write:

```js
    '@elderjs/plugin-markdown': {
      routes: ['blog'],
      remarkPlugins: [
        [require("remark-shiki-twoslash"), { theme: "nord"}]
      ]
    },
```

But that crashes the template because it (very reasonably) assumes the availability of yml front-matter. Ideally I could do something like:

```js
    '@elderjs/plugin-markdown': {
      routes: ['blog'],
      remarkPlugins: [
         ...require("@elderjs/plugin-markdown").plugins,
        [require("remark-shiki-twoslash"), { theme: "nord"}]
      ]
    },
```

**Comment by nickreese** [comment]
@orta Huge fan of your work. As I mentioned in discord, Elder.js has a massive API surface so trying to keep the plugins relatively minimal. :) 

100% open to a PR here. 

Based on the current setup, not sure the `...array` would overwrite:

```js
const plugins = [
        remarkFrontmatter,
        [extractFrontmatter, { name: 'frontmatter', yaml: yaml }],
        remarkSlug,
        remarkHtml,
];
```

It is almost as if we'd need a dedicated code parsing key on the config.

**Comment by nickreese** [comment]
The default remarkPlugins are exported for ease of use via the package. 

```js
const { remarkPlugins } = require('@elderjs/plugin-markdown');
``` 

But the above example still may not work because the order of imports matters.
