### ISSUE TITLE
[Seo-check]: preferences doesn't work ?

### ISSUE THREAD

**Issue by kiuKisas** [Elderjs/plugins#99]
Here is my config regarding `plugin-seo-check`:
```
    '@elderjs/plugin-seo-check': {
      display: process.NODE_ENV === 'production' ? ['errors', 'warnings'] : [], // disables reporting unless you in production building.
      preferences: {
        internalLinksLowerCase: true,
        internalLinksTrailingSlash: false
      },
      writeLocation: './report.json',
    },

```
But I still have warning `Internal links should include a trailing slash`, did I miss something ?

**Comment by nickreese** [comment]
@kiuKisas The config wasn't piped over. Not sure how I was able to run the deploy scripts with uncommitted changes. Shipping an update.
